all: clean git/submodule cmake/build cmake/test

cmake/test:
	cd build && ctest

cmake/build:
	mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. -Dwithout-static=ON && make

cpplint:
	cpplint --recursive ./{src,include,example}/

git/submodule:
	git submodule update --init

.PHONY: clean
clean:
	rm -rf build
